# Generated by Django 5.0 on 2025-09-03 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
                ('nome', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
                ('valor', models.FloatField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
