# Generated by Django 5.0 on 2025-09-03 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
